# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('challanid', models.CharField(max_length=255)),
                ('process', models.CharField(max_length=10)),
                ('qty', models.IntegerField(default=0)),
                ('assignmentdate', models.DateField()),
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'assignments',
                'managed': True,
                'verbose_name_plural': 'Assignments',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('billingid', models.IntegerField(primary_key=True, serialize=False)),
                ('billingdate', models.DateField(blank=True, null=True)),
                ('amountpaid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bills',
                'managed': True,
                'verbose_name_plural': 'Bills',
            },
        ),
        migrations.CreateModel(
            name='Karigar',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('profile', models.CharField(choices=[('stitch', 'Stitch'), ('block', 'Block'), ('emb', 'Embroider'), ('wash', 'Wash'), ('addon', 'Addon')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('pan', models.CharField(blank=True, max_length=11, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='karigars/')),
            ],
            options={
                'db_table': 'karigars',
                'managed': True,
                'verbose_name_plural': 'Karigars',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prodid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('colour', models.CharField(blank=True, max_length=100, null=True)),
                ('fabric', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('cost_stitch', models.IntegerField(blank=True, null=True)),
                ('cost_block', models.IntegerField(blank=True, null=True)),
                ('cost_emb', models.IntegerField(blank=True, null=True)),
                ('cost_wash', models.IntegerField(blank=True, null=True)),
                ('cost_addon', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': True,
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='karigar',
            field=models.ForeignKey(blank=True, db_column='karigar', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='AnIndianStory.Karigar'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='karigar',
            field=models.ForeignKey(db_column='karigar', on_delete=django.db.models.deletion.DO_NOTHING, to='AnIndianStory.Karigar'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='product',
            field=models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.DO_NOTHING, to='AnIndianStory.Product'),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together=set([('challanid', 'process', 'karigar', 'product')]),
        ),
    ]
