# Generated by Django 3.2.5 on 2021-07-28 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnIndianStory', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('prodid', 'company')},
        ),
    ]
