# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnIndianStory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignments',
            options={'managed': False, 'verbose_name_plural': 'Assignments'},
        ),
        migrations.AlterModelOptions(
            name='bills',
            options={'managed': False, 'verbose_name_plural': 'Bills'},
        ),
        migrations.AlterModelOptions(
            name='karigars',
            options={'managed': False, 'verbose_name_plural': 'Karigars'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'managed': False, 'verbose_name_plural': 'Products'},
        ),
    ]
