# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnIndianStory', '0002_auto_20160627_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('challanid', models.IntegerField()),
                ('process', models.CharField(max_length=10)),
                ('qty', models.IntegerField(default=0)),
                ('assignmentdate', models.DateField()),
                ('assignment_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'assignments',
                'managed': False,
                'verbose_name_plural': 'Assignments',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('billingid', models.IntegerField(primary_key=True, serialize=False)),
                ('billingdate', models.DateField(blank=True, null=True)),
                ('amountpaid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bills',
                'managed': False,
                'verbose_name_plural': 'Bills',
            },
        ),
        migrations.CreateModel(
            name='Karigar',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('profile', models.CharField(choices=[('stitch', 'Stitch'), ('block', 'Block'), ('emb', 'Embroider'), ('wash', 'Wash'), ('addon', 'Addon')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='karigars/')),
            ],
            options={
                'db_table': 'karigars',
                'managed': False,
                'verbose_name_plural': 'Karigars',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prodid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('colour', models.CharField(blank=True, max_length=100, null=True)),
                ('fabric', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('cost_stitch', models.IntegerField(blank=True, null=True)),
                ('cost_block', models.IntegerField(blank=True, null=True)),
                ('cost_emb', models.IntegerField(blank=True, null=True)),
                ('cost_wash', models.IntegerField(blank=True, null=True)),
                ('cost_addon', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
                'verbose_name_plural': 'Products',
            },
        ),
    ]
