# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-09-11 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnIndianStory', '0003_auto_20170709_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karigar',
            name='profile',
            field=models.CharField(choices=[('stitch', 'Stitch'), ('block', 'Block'), ('emb', 'Embroider'), ('wash', 'Wash'), ('addon', 'Addon'), ('finish', 'Finish')], max_length=20),
        ),
    ]
